<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="robot_materials.urdf.xacro" />
    <xacro:include filename="inertia_formulas.urdf.xacro" />

    <xacro:property name="base_length" value = "0.6"/>
    <xacro:property name="base_width" value = "0.4"/>
    <xacro:property name="base_height" value = "0.2"/>
    <xacro:property name="base_mass" value = "5"/>
    <xacro:property name="wheel_radius" value = "0.07"/>
    <xacro:property name="wheel_height" value = "0.05"/>
    <xacro:property name="wheel_mass" value = "4"/>
    <xacro:property name="front_wheel_mass" value = "2"/>

    <xacro:macro name="wheel_link" params ="prefix r h z">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${r}" length="${h}" />                
                </geometry>
                <origin xyz="0 0 ${z}" rpy="0 0 0" />   
                <material name="red"/>            
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${r}" length="${h}" />                
                    </geometry>
                    <origin xyz="0 0 ${z}" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia mass ="${1*wheel_mass}" radius ="${2*wheel_radius}" height="${2*wheel_height}" xyz="0 0 ${z}" rpy="0 0 0"/>
        </link>
    </xacro:macro>
    
    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />                
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />   
            <!-- the origin tell us location to the base -->
            <!-- add material here for color -->
            <material name="green"/>            
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />                
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
        </collision>
        <xacro:cuboid_inertia mass ="${base_mass}" length="${2*base_length}" width="${2*base_width}" height="${2*base_height}" xyz="0 0 0.1" rpy="0 0 0"/>
    </link>

    <link name="second_link">
        <visual>
            <geometry>

                <cylinder radius="0.1" length="0.2" />                
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />   
            <!-- the origin tell us location to the base -->
            <!-- add material here for color -->
            <material name="blue"/>            
        </visual>
        <collision>
            <geometry>

                <cylinder radius="0.1" length="0.2" />                
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" /> 
        </collision>
        <xacro:cylinder_inertia mass ="${wheel_mass}" radius ="${2*0.1}" height="${2*0.2}" xyz="0 0 0.1" rpy="0 0 0"/>
    </link>

   <xacro:wheel_link prefix="left" r ="${wheel_radius}" h= "${wheel_height}" z="${-1*wheel_height*0.5}"/>
   <xacro:wheel_link prefix="right" r ="${wheel_radius}" h= "${wheel_height}" z="${wheel_height*0.5}"/>

    <link name="front_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>                
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />   
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>                
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia mass ="${front_wheel_mass}" radius="${2*wheel_radius/2}" xyz="0 0 0" rpy="0 0 0"/>
    </link>

    <link name="base_foot_print"/>

    <joint name="base_foot_print_joint" type ="fixed">
        <parent link="base_foot_print" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <joint name="base_front_wheel_joint" type ="continuous">
        <parent link="base_link" />
        <child link="front_wheel_link" />
        <origin xyz="0.2 0 -0.035" rpy="0 0 0" />
        <axis xyz="0 1 0" />  
    </joint>

    <joint name="base_right_wheel_joint" type ="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="-0.2 -0.2 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1" />  
    </joint>

    <joint name="base_left_wheel_joint" type ="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-0.2 0.2 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1" />  
    </joint>

    <joint name="base_second_joint" type ="prismatic">
        <parent link="base_link" />
        <child link="second_link" />
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <!-- rotate above z using the syuntax below -->
        <axis xyz="1 0 0" />  
        <limit lower="0.0" upper="0.2" velocity ="100" effort="100"/>
        
    </joint>
    

</robot>